# Generated by Django 5.1.2 on 2024-10-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
